[custom_groups]
; 格式：策略组名`url-test`匹配节点的正则表达式`测试网址`测速间隔(秒)`容差(ms)
♻️ 自动选择 - HK`url-test`(?i)HK|香港|HongKong`http://www.gstatic.com/generate_204`300`50
♻️ 自动选择 - US`url-test`(?i)US|美国|States`http://www.gstatic.com/generate_204`300`50
♻️ 自动选择 - JP`url-test`(?i)JP|日本|Tokyo|Osaka`http://www.gstatic.com/generate_204`300`50
♻️ 自动选择 - KR`url-test`(?i)KR|韩国|Korea|Seoul`http://www.gstatic.com/generate_204`300`50
♻️ 自动选择 - SG`url-test`(?i)SG|新加坡|Singapore`http://www.gstatic.com/generate_204`300`50

; 代理分组，让节点可以被正常选中
; ✨ 优化：已将 KR 和 SG 的自动选择组绑定到主菜单中
🚀 节点选择`select`.*`♻️ 自动选择 - HK`♻️ 自动选择 - US`♻️ 自动选择 - JP`♻️ 自动选择 - KR`♻️ 自动选择 - SG`DIRECT
